[phases.setup]
nixPkgs = ["jdk17_headless", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests -B"]

[start]
cmd = "java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0 -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+ExitOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -jar target/martinis.jar"
