# Railway Configuration
# Note: Multi-service templates are created through Railway's dashboard UI
# This file is kept for reference but Railway templates are now managed via the Railway UI

# To create a deploy button:
# 1. Deploy your project to Railway manually
# 2. Go to project settings and convert it to a template
# 3. Get your template code
# 4. Use: https://railway.com/new/template/{YOUR_TEMPLATE_CODE}

# For service-specific configuration, use railway.json instead
# This file is deprecated for multi-service configuration
