-- Initial data for Railway MySQL
-- This will auto-run after schema.sql when the application starts
-- Uses INSERT IGNORE to skip if data already exists, preserving data across deployments

-- No default users are created for security reasons.
-- To create an initial admin user, use environment variables:
--   ADMIN_USERNAME - The username for the admin account
--   ADMIN_PASSWORD - The password for the admin account (will be BCrypt hashed)
--   ADMIN_FIRSTNAME - (Optional) First name for the admin user
--   ADMIN_LASTNAME - (Optional) Last name for the admin user
--
-- Users will be created programmatically when these environment variables are set.
-- See DatabaseInitializer.java for implementation details.
